### ISSUE TITLE
No npm reposiroty?

### ISSUE THREAD

**Issue by Alxmerino** [benjamin-smith/gulp-cache-break#2]
Can we have this as an NPM repository so we can do something like.

``` bash
npm install --save-dev gulp-cache-break
```

**Comment by benjamin-smith** [comment]
The only reason I have not included on NPM is that this module does not play nicely with streams. Considering that many gulp plugins do not, I should add it for those that find it useful. I'll take care of that today. Thanks @Alxmerino!

**Comment by Alxmerino** [comment]
Thanks for your response @benjamin-smith !

**Comment by benjamin-smith** [comment]
I'd try https://github.com/benjamin-smith/gulp-cache-break/issues/2#issuecomment-123336853 in lieu of this repo.
